apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: logging
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp